INHERIT: mkdocs-base.yaml

site_name: "KRL - Log Pipelines with Bindplane"
site_url: "https://dt-arr.github.io/enablement-bindplane-logs/"
repo_name: "KRL - View Code on GitHub"
repo_url: "https://github.com/dt-arr/enablement-bindplane-logs"
nav:
  - "1. About": index.md
  - "2. Getting started": 2-getting-started.md
  - "3. Installing the Bindplane Agent": 3-bindplane-agent.md
  - "4. Bindplane Configuration": 4-bindplane-configuration.md
  - "5. Processors: Add a Field": 5-add-field.md
  - "6. Structured Field Extraction": pipeline-field-extraction.md
  - "7. Volume Reduction": pipeline-volume-reduction.md
  - "8. Severity Enrichment": pipeline-severity-enrichment.md
  - "9. Security Context Tagging": pipeline-security-context.md
  - "10. Parsing with OpenPipeline": 6-parsing-with-openpipeline.md
  - "11. Bindplane Health": 9-bindplane-health.md
  - "12. Masking Sensitive Data": 7-masking-routing.md
  - "13. Extracting Metrics from Logs": 8-metric-extraction.md
  - "14. Quick Reference": 10-quick-reference.md

extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/7c50bce5c0cc890f_complete.js"
